AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: <your stack description here>
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Api
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /stream/:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetStreamData.Arn}/invocations
              parameters:
                - name: start_time
                  in: query
                  required: true
                  schema:
                    type: string
                    pattern: ^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}$
                - name: end_time
                  in: query
                  required: true
                  schema:
                    type: string
                    pattern: ^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}$
              responses: {}
          /stats/:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetStats.Arn}/invocations
              responses: {}
          /transaction/{txn_hash}/:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTransaction.Arn}/invocations
              parameters:
                - name: txn_hash
                  in: path
                  required: true
                  schema:
                    type: string
                    pattern: ^0x[a-f0-9]{24,128}$
              responses: {}
          /block/{block_hash}/:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetBlock.Arn}/invocations
              parameters:
                - name: block_hash
                  in: path
                  required: true
                  schema:
                    type: string
                    pattern: ^(0x[a-f0-9]{24,128}|initial)$
                - name: full
                  in: query
                  required: false
                  schema:
                    type: boolean
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5
  TransactionBlockStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 5
      RetentionPeriodHours: 24
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      StreamModeDetails:
        StreamMode: PROVISIONED
  TransactionBlockPublisher:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: TransactionBlockPublisher
      CodeUri: src/TransactionBlockPublisher
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Events:
        TransactionBlockStream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt TransactionBlockStream.Arn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
      Environment:
        Variables:
          RDS_PORT: !Ref RDSPort
          RDS_HOSTNAME: !Ref RDSHostname
          RDS_SECRETARN: !Ref RDSSecretArn
          RDS_DB_NAME: !Ref RDSDBName
          RDS_REGION: !Ref AWS::Region
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref RDSSecretArn
      Role: !GetAtt TransactionBlockPublisherRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnet1
          - !Ref VPCSubnet2
          - !Ref VPCSubnet3
  TransactionBlockPublisherLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${TransactionBlockPublisher}
  TransactionBlockPublisherRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TransactionBlockPublisherRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:DescribeStream
                  - kinesis:GetShardIterator
                  - kinesis:GetRecords
                Resource: !GetAtt TransactionBlockStream.Arn
              - Effect: Allow
                Action:
                  - rds-data:ExecuteStatement
                Resource: !Ref RDSProxyArn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref RDSSecretArn
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AttachNetworkInterface
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*
  GetStreamData:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetStreamData
      CodeUri: src/GetStreamData
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 60
      Tracing: Active
      Events:
        ApiGET:
          Type: Api
          Properties:
            Path: /stream/
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          RDS_PORT: !Ref RDSPort
          RDS_HOSTNAME: !Ref RDSHostname
          RDS_SECRETARN: !Ref RDSSecretArn
          RDS_DB_NAME: !Ref RDSDBName
          RDS_REGION: !Ref AWS::Region
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref RDSSecretArn
      Role: !GetAtt GetStreamDataRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnet1
          - !Ref VPCSubnet2
          - !Ref VPCSubnet3
  GetStreamDataLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetStreamData}
  GetStreamDataRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetStreamDataRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-data:ExecuteStatement
                Resource: !Ref RDSProxyArn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref RDSSecretArn
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AttachNetworkInterface
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*
  GetStats:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetStats
      CodeUri: src/GetStats
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        ApiGETstats:
          Type: Api
          Properties:
            Path: /stats/
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          RDS_PORT: !Ref RDSPort
          RDS_HOSTNAME: !Ref RDSHostname
          RDS_SECRETARN: !Ref RDSSecretArn
          RDS_DB_NAME: !Ref RDSDBName
          RDS_REGION: !Ref AWS::Region
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref RDSSecretArn
      Role: !GetAtt GetStatsRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnet1
          - !Ref VPCSubnet2
          - !Ref VPCSubnet3
  GetStatsLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetStats}
  GetStatsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetStatsRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-data:ExecuteStatement
                Resource: !Ref RDSProxyArn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref RDSSecretArn
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AttachNetworkInterface
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*
  GetTransaction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetTransaction
      CodeUri: src/GetTransaction
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          RDS_PORT: !Ref RDSPort
          RDS_HOSTNAME: !Ref RDSHostname
          RDS_SECRETARN: !Ref RDSSecretArn
          RDS_DB_NAME: !Ref RDSDBName
          RDS_REGION: !Ref AWS::Region
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref RDSSecretArn
      Events:
        ApiGETtransaction:
          Type: Api
          Properties:
            Path: /transaction/{txn_hash}/
            Method: GET
            RestApiId: !Ref Api
      Role: !GetAtt GetTransactionRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnet1
          - !Ref VPCSubnet2
          - !Ref VPCSubnet3
  GetTransactionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetTransaction}
  GetTransactionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetTransactionRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-data:ExecuteStatement
                Resource: !Ref RDSProxyArn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref RDSSecretArn
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AttachNetworkInterface
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*
  GetBlock:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetBlock
      CodeUri: src/GetBlock
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        ApiGETblock:
          Type: Api
          Properties:
            Path: /block/{block_hash}/
            Method: GET
            RestApiId: !Ref Api
      Role: !GetAtt GetBlockRole.Arn
      Environment:
        Variables:
          RDS_PORT: !Ref RDSPort
          RDS_HOSTNAME: !Ref RDSHostname
          RDS_SECRETARN: !Ref RDSSecretArn
          RDS_DB_NAME: !Ref RDSDBName
          RDS_REGION: !Ref AWS::Region
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref RDSSecretArn
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnet1
          - !Ref VPCSubnet2
          - !Ref VPCSubnet3
  GetBlockLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetBlock}
  GetBlockRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetBlockRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-data:ExecuteStatement
                Resource: !Ref RDSProxyArn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref RDSSecretArn
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AttachNetworkInterface
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*
Metadata:
  AWS::Composer::ExternalResources:
    RDS:
      Type: externalRDS
      Settings:
        Port: !Ref RDSPort
        Hostname: !Ref RDSHostname
        SecretArn: !Ref RDSSecretArn
        Arn: !Ref RDSProxyArn
Parameters:
  RDSPort:
    Type: Number
  RDSHostname:
    Type: String
  RDSSecretArn:
    Type: String
  RDSProxyArn:
    Type: String
  RDSDBName:
    Type: String
  VPCSecurityGroup:
    Type: String
  VPCSubnet1:
    Type: String
  VPCSubnet2:
    Type: String
  VPCSubnet3:
    Type: String
Outputs:
  TransactionBlockStreamArn:
    Description: The ARN of the Kinesis stream
    Value: !GetAtt TransactionBlockStream.Arn
  TransactionBlockStreamName:
    Description: The name of the Kinesis stream
    Value: !Ref TransactionBlockStream
  ApiEndpoint:
    Description: The endpoint URL for the backend API
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/